/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CUB_H_RPCGEN
#define _CUB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CUB 0x20000002
#define VCUB 1

#if defined(__STDC__) || defined(__cplusplus)
#define tirada 1
extern  int * tirada_1(CLIENT *);
extern  int * tirada_1_svc(struct svc_req *);
extern int cub_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define tirada 1
extern  int * tirada_1();
extern  int * tirada_1_svc();
extern int cub_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CUB_H_RPCGEN */
