/*	Archivo: cub_client.c
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "cub.h"
void
cub_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
#ifndef	DEBUG
	clnt = clnt_create (host, CUB, VCUB, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_1 = tirada_1(clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("RESULTADO DE LA TIRADA DE UN DADO: %d \n", *result_1 ); /* agregado */
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cub_1 (host);
exit (0);
}
/* Fin del archivo: cub_client.c */
