/*	Archivo: cub_server.c
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "cub.h"

int *
tirada_1_svc(struct svc_req *rqstp)
{
	static int  result;
	/* agregado */
	result = ((random() % 6) + 1);
	return &result;
}
/* Fin del archivo: cub_server.c */
